### ISSUE TITLE
Create Weapon

### ISSUE THREAD

**Issue by bashnia007** [bashnia007/BangGame#17]
Create weapon class and map it to weapon card

**Comment by IvanovAndrew** [comment]
Also I implemented this rules:
(*) you can have only 1 copy of any one card in play;
(one card is a copy of another if they have the same name)
(*) you can have only 1 weapon in play.
(when you play a new weapon, discard the one you have in play)

**Comment by bashnia007** [comment]
Just small mistakes:
'these rules' instead of 'this rules'
'in game' I suppose, not 'in play'
