### ISSUE TITLE
Implement effect of beer card

### ISSUE THREAD

**Issue by bashnia007** [bashnia007/BangGame#32]

**Comment by IvanovAndrew** [comment]
From rules

> **Beer**
> This  card  lets  you  regain one life point – take a bullet from the pile. You cannot gain more life points than your  starting  amount! 
> The  Beer  cannot  be  used to help other players.
> The Beer can be played in two ways:
> •	 as  usual,  during  your turn;
> •	 out  of  turn,  but  only  if  you  have  just received a hit that is lethal (i.e. a hit that takes away your last life point), and not if you are simply hit.
> Beer has no effect if there are only 2 players left in the game; in other words, if you play a Beer you do not gain any life point.
