### ISSUE TITLE
Implement effect of saloon card

### ISSUE THREAD

**Issue by bashnia007** [bashnia007/BangGame#33]

**Comment by IvanovAndrew** [comment]
From rules
> **Saloon**
> Cards  with  symbols  on  two  lines  have  two  simultaneous effects, one for each line.
> Here symbols say: “Regain one life point”, and this applies to “All the other players”, and on the next line: “[You] regain one life point”.
> The  overall  effect  is  that  all  players  in  play  regain  one life point.
> You cannot play a Saloon out of turn when you are losing your last life point: the Saloon is not a Beer!
