### ISSUE TITLE
Implement effect of gatling card

### ISSUE THREAD

**Issue by bashnia007** [bashnia007/BangGame#34]

**Comment by IvanovAndrew** [comment]
From rules
> **Gatling**
> The  Gatling  shoots  “a  BANG!”  to  “all  the  other  players”, regardless of the distance. Even though the Gatling shoots a BANG! to all the other players, it is not considered a BANG! card. During your turn you can play any number of Gatling, but only one BANG! card.
>

**Comment by bashnia007** [comment]
#68
