### ISSUE TITLE
Implement effect of jail card

### ISSUE THREAD

**Issue by bashnia007** [bashnia007/BangGame#41]

**Comment by IvanovAndrew** [comment]
> **Jail**
> Play this card in front of any player regardless of the distance: 
> you put him in jail! If you are in jail, you must “draw!” before the beginning of your turn:
> - if you draw a Heart card, you escape from jail: discard the Jail, and continue your turn as normal;
> - otherwise discard the Jail and skip your turn.
>
> If you are in Jail you remain a possible target for BANG! cards and can still play response cards (e.g. Missed! and Beer) out of your turn, if necessary.
> Jail cannot be played on the Sheriff.
