### ISSUE TITLE
Implement effect of Dynamite card

### ISSUE THREAD

**Issue by bashnia007** [bashnia007/BangGame#44]

**Comment by IvanovAndrew** [comment]
> **Dynamite**
> Play this card in front of you: the Dynamite will stay there for a whole turn. 
> When  you  start  your  next  turn  (you  have  the  Dynamite  already  in  play), before the first phase you must “draw!”:
> -  if you draw a card showing Spades and a number between 2 and 9, the Dynamite explodes! Discard it and lose 3 life points;
> -  otherwise,  pass  the  Dynamite  to  the  player  on  your  left (who will “draw!” on his turn, etc.).
> 
> Players keep passing the Dynamite around until it explodes, with the effect explained above, or it is drawn or discarded by a Panic! or a Cat Balou. If you have both the Dynamite and a Jail in play, check the Dynamite rst. If you are damaged (or even eliminated!) by a Dynamite, this damage is not considered to be caused by any player.
>
