### ISSUE TITLE
Implement effect of duel card

### ISSUE THREAD

**Issue by bashnia007** [bashnia007/BangGame#45]

**Comment by IvanovAndrew** [comment]
> **Duel**
> With  this  card  you  can  challenge  any  other player  (staring  him  in  the  eyes!),  regardless 
> of the distance. The challenged player may discard a BANG! card (even though it is not his turn!). If he does, you may discard a BANG! card, and so on: the first player failing to discard a BANG! card loses one life point, and the duel is I over. You cannot play Missed! or use the Barrel during a duel.
> 
> The Duel is not a BANG! card. BANG! cards discarded during a Duel are not accounted towards the "one BANG! card" limitation.
